# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Test

defaults:
  run:
    shell: bash

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  testing:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit tests
        run: cargo test
      - name: Integration tests
        run: ./ci.sh
